sudo : required
language: java
before_install:
  - sudo add-apt-repository ppa:cwchien/gradle -y
  - sudo apt-get update -y
  - sudo apt-get install gradle -y
  - gradle setupCiWorkspace
script:
  - gradle build
